apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-pipelinerun
spec:
  pipelineRef:
    name: example-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: your-pvc
