apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: cleanup-task
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: nose-task
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: shared-workspace
